apiVersion: v1
kind: Service
metadata:
  name: battle-server
spec:
  type: ClusterIP
  selector:
    app: battle-server
  ports:
    - name: http
      port: 3000        # Service のポート
      targetPort: 3000  # コンテナのポート
